// WARNING: File autogenerated DO NOT modify
// https://www.khronos.org/registry/OpenGL/api/GLES2/gl2.h
@file:Suppress("unused", "RedundantUnitReturnType")

package com.soywiz.kmedialayer

open class KmlGlProxy(val parent: KmlGl) : KmlGl() {
    open fun before(name: String): Unit = Unit
    open fun after(name: String): Unit = Unit
    override fun activeTexture(texture: Int): Unit {
       before("activeTexture")
       val res = parent.activeTexture(texture)
       after("activeTexture")
       return res
    }
    override fun attachShader(program: Int, shader: Int): Unit {
       before("attachShader")
       val res = parent.attachShader(program, shader)
       after("attachShader")
       return res
    }
    override fun bindAttribLocation(program: Int, index: Int, name: String): Unit {
       before("bindAttribLocation")
       val res = parent.bindAttribLocation(program, index, name)
       after("bindAttribLocation")
       return res
    }
    override fun bindBuffer(target: Int, buffer: Int): Unit {
       before("bindBuffer")
       val res = parent.bindBuffer(target, buffer)
       after("bindBuffer")
       return res
    }
    override fun bindFramebuffer(target: Int, framebuffer: Int): Unit {
       before("bindFramebuffer")
       val res = parent.bindFramebuffer(target, framebuffer)
       after("bindFramebuffer")
       return res
    }
    override fun bindRenderbuffer(target: Int, renderbuffer: Int): Unit {
       before("bindRenderbuffer")
       val res = parent.bindRenderbuffer(target, renderbuffer)
       after("bindRenderbuffer")
       return res
    }
    override fun bindTexture(target: Int, texture: Int): Unit {
       before("bindTexture")
       val res = parent.bindTexture(target, texture)
       after("bindTexture")
       return res
    }
    override fun blendColor(red: Float, green: Float, blue: Float, alpha: Float): Unit {
       before("blendColor")
       val res = parent.blendColor(red, green, blue, alpha)
       after("blendColor")
       return res
    }
    override fun blendEquation(mode: Int): Unit {
       before("blendEquation")
       val res = parent.blendEquation(mode)
       after("blendEquation")
       return res
    }
    override fun blendEquationSeparate(modeRGB: Int, modeAlpha: Int): Unit {
       before("blendEquationSeparate")
       val res = parent.blendEquationSeparate(modeRGB, modeAlpha)
       after("blendEquationSeparate")
       return res
    }
    override fun blendFunc(sfactor: Int, dfactor: Int): Unit {
       before("blendFunc")
       val res = parent.blendFunc(sfactor, dfactor)
       after("blendFunc")
       return res
    }
    override fun blendFuncSeparate(sfactorRGB: Int, dfactorRGB: Int, sfactorAlpha: Int, dfactorAlpha: Int): Unit {
       before("blendFuncSeparate")
       val res = parent.blendFuncSeparate(sfactorRGB, dfactorRGB, sfactorAlpha, dfactorAlpha)
       after("blendFuncSeparate")
       return res
    }
    override fun bufferData(target: Int, size: Int, data: KmlBuffer, usage: Int): Unit {
       before("bufferData")
       val res = parent.bufferData(target, size, data, usage)
       after("bufferData")
       return res
    }
    override fun bufferSubData(target: Int, offset: Int, size: Int, data: KmlBuffer): Unit {
       before("bufferSubData")
       val res = parent.bufferSubData(target, offset, size, data)
       after("bufferSubData")
       return res
    }
    override fun checkFramebufferStatus(target: Int): Int {
       before("checkFramebufferStatus")
       val res = parent.checkFramebufferStatus(target)
       after("checkFramebufferStatus")
       return res
    }
    override fun clear(mask: Int): Unit {
       before("clear")
       val res = parent.clear(mask)
       after("clear")
       return res
    }
    override fun clearColor(red: Float, green: Float, blue: Float, alpha: Float): Unit {
       before("clearColor")
       val res = parent.clearColor(red, green, blue, alpha)
       after("clearColor")
       return res
    }
    override fun clearDepthf(d: Float): Unit {
       before("clearDepthf")
       val res = parent.clearDepthf(d)
       after("clearDepthf")
       return res
    }
    override fun clearStencil(s: Int): Unit {
       before("clearStencil")
       val res = parent.clearStencil(s)
       after("clearStencil")
       return res
    }
    override fun colorMask(red: Boolean, green: Boolean, blue: Boolean, alpha: Boolean): Unit {
       before("colorMask")
       val res = parent.colorMask(red, green, blue, alpha)
       after("colorMask")
       return res
    }
    override fun compileShader(shader: Int): Unit {
       before("compileShader")
       val res = parent.compileShader(shader)
       after("compileShader")
       return res
    }
    override fun compressedTexImage2D(target: Int, level: Int, internalformat: Int, width: Int, height: Int, border: Int, imageSize: Int, data: KmlBuffer): Unit {
       before("compressedTexImage2D")
       val res = parent.compressedTexImage2D(target, level, internalformat, width, height, border, imageSize, data)
       after("compressedTexImage2D")
       return res
    }
    override fun compressedTexSubImage2D(target: Int, level: Int, xoffset: Int, yoffset: Int, width: Int, height: Int, format: Int, imageSize: Int, data: KmlBuffer): Unit {
       before("compressedTexSubImage2D")
       val res = parent.compressedTexSubImage2D(target, level, xoffset, yoffset, width, height, format, imageSize, data)
       after("compressedTexSubImage2D")
       return res
    }
    override fun copyTexImage2D(target: Int, level: Int, internalformat: Int, x: Int, y: Int, width: Int, height: Int, border: Int): Unit {
       before("copyTexImage2D")
       val res = parent.copyTexImage2D(target, level, internalformat, x, y, width, height, border)
       after("copyTexImage2D")
       return res
    }
    override fun copyTexSubImage2D(target: Int, level: Int, xoffset: Int, yoffset: Int, x: Int, y: Int, width: Int, height: Int): Unit {
       before("copyTexSubImage2D")
       val res = parent.copyTexSubImage2D(target, level, xoffset, yoffset, x, y, width, height)
       after("copyTexSubImage2D")
       return res
    }
    override fun createProgram(): Int {
       before("createProgram")
       val res = parent.createProgram()
       after("createProgram")
       return res
    }
    override fun createShader(type: Int): Int {
       before("createShader")
       val res = parent.createShader(type)
       after("createShader")
       return res
    }
    override fun cullFace(mode: Int): Unit {
       before("cullFace")
       val res = parent.cullFace(mode)
       after("cullFace")
       return res
    }
    override fun deleteBuffers(n: Int, items: KmlBuffer): Unit {
       before("deleteBuffers")
       val res = parent.deleteBuffers(n, items)
       after("deleteBuffers")
       return res
    }
    override fun deleteFramebuffers(n: Int, items: KmlBuffer): Unit {
       before("deleteFramebuffers")
       val res = parent.deleteFramebuffers(n, items)
       after("deleteFramebuffers")
       return res
    }
    override fun deleteProgram(program: Int): Unit {
       before("deleteProgram")
       val res = parent.deleteProgram(program)
       after("deleteProgram")
       return res
    }
    override fun deleteRenderbuffers(n: Int, items: KmlBuffer): Unit {
       before("deleteRenderbuffers")
       val res = parent.deleteRenderbuffers(n, items)
       after("deleteRenderbuffers")
       return res
    }
    override fun deleteShader(shader: Int): Unit {
       before("deleteShader")
       val res = parent.deleteShader(shader)
       after("deleteShader")
       return res
    }
    override fun deleteTextures(n: Int, items: KmlBuffer): Unit {
       before("deleteTextures")
       val res = parent.deleteTextures(n, items)
       after("deleteTextures")
       return res
    }
    override fun depthFunc(func: Int): Unit {
       before("depthFunc")
       val res = parent.depthFunc(func)
       after("depthFunc")
       return res
    }
    override fun depthMask(flag: Boolean): Unit {
       before("depthMask")
       val res = parent.depthMask(flag)
       after("depthMask")
       return res
    }
    override fun depthRangef(n: Float, f: Float): Unit {
       before("depthRangef")
       val res = parent.depthRangef(n, f)
       after("depthRangef")
       return res
    }
    override fun detachShader(program: Int, shader: Int): Unit {
       before("detachShader")
       val res = parent.detachShader(program, shader)
       after("detachShader")
       return res
    }
    override fun disable(cap: Int): Unit {
       before("disable")
       val res = parent.disable(cap)
       after("disable")
       return res
    }
    override fun disableVertexAttribArray(index: Int): Unit {
       before("disableVertexAttribArray")
       val res = parent.disableVertexAttribArray(index)
       after("disableVertexAttribArray")
       return res
    }
    override fun drawArrays(mode: Int, first: Int, count: Int): Unit {
       before("drawArrays")
       val res = parent.drawArrays(mode, first, count)
       after("drawArrays")
       return res
    }
    override fun drawElements(mode: Int, count: Int, type: Int, indices: Int): Unit {
       before("drawElements")
       val res = parent.drawElements(mode, count, type, indices)
       after("drawElements")
       return res
    }
    override fun enable(cap: Int): Unit {
       before("enable")
       val res = parent.enable(cap)
       after("enable")
       return res
    }
    override fun enableVertexAttribArray(index: Int): Unit {
       before("enableVertexAttribArray")
       val res = parent.enableVertexAttribArray(index)
       after("enableVertexAttribArray")
       return res
    }
    override fun finish(): Unit {
       before("finish")
       val res = parent.finish()
       after("finish")
       return res
    }
    override fun flush(): Unit {
       before("flush")
       val res = parent.flush()
       after("flush")
       return res
    }
    override fun framebufferRenderbuffer(target: Int, attachment: Int, renderbuffertarget: Int, renderbuffer: Int): Unit {
       before("framebufferRenderbuffer")
       val res = parent.framebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer)
       after("framebufferRenderbuffer")
       return res
    }
    override fun framebufferTexture2D(target: Int, attachment: Int, textarget: Int, texture: Int, level: Int): Unit {
       before("framebufferTexture2D")
       val res = parent.framebufferTexture2D(target, attachment, textarget, texture, level)
       after("framebufferTexture2D")
       return res
    }
    override fun frontFace(mode: Int): Unit {
       before("frontFace")
       val res = parent.frontFace(mode)
       after("frontFace")
       return res
    }
    override fun genBuffers(n: Int, buffers: KmlBuffer): Unit {
       before("genBuffers")
       val res = parent.genBuffers(n, buffers)
       after("genBuffers")
       return res
    }
    override fun generateMipmap(target: Int): Unit {
       before("generateMipmap")
       val res = parent.generateMipmap(target)
       after("generateMipmap")
       return res
    }
    override fun genFramebuffers(n: Int, framebuffers: KmlBuffer): Unit {
       before("genFramebuffers")
       val res = parent.genFramebuffers(n, framebuffers)
       after("genFramebuffers")
       return res
    }
    override fun genRenderbuffers(n: Int, renderbuffers: KmlBuffer): Unit {
       before("genRenderbuffers")
       val res = parent.genRenderbuffers(n, renderbuffers)
       after("genRenderbuffers")
       return res
    }
    override fun genTextures(n: Int, textures: KmlBuffer): Unit {
       before("genTextures")
       val res = parent.genTextures(n, textures)
       after("genTextures")
       return res
    }
    override fun getActiveAttrib(program: Int, index: Int, bufSize: Int, length: KmlBuffer, size: KmlBuffer, type: KmlBuffer, name: KmlBuffer): Unit {
       before("getActiveAttrib")
       val res = parent.getActiveAttrib(program, index, bufSize, length, size, type, name)
       after("getActiveAttrib")
       return res
    }
    override fun getActiveUniform(program: Int, index: Int, bufSize: Int, length: KmlBuffer, size: KmlBuffer, type: KmlBuffer, name: KmlBuffer): Unit {
       before("getActiveUniform")
       val res = parent.getActiveUniform(program, index, bufSize, length, size, type, name)
       after("getActiveUniform")
       return res
    }
    override fun getAttachedShaders(program: Int, maxCount: Int, count: KmlBuffer, shaders: KmlBuffer): Unit {
       before("getAttachedShaders")
       val res = parent.getAttachedShaders(program, maxCount, count, shaders)
       after("getAttachedShaders")
       return res
    }
    override fun getAttribLocation(program: Int, name: String): Int {
       before("getAttribLocation")
       val res = parent.getAttribLocation(program, name)
       after("getAttribLocation")
       return res
    }
    override fun getUniformLocation(program: Int, name: String): Int {
       before("getUniformLocation")
       val res = parent.getUniformLocation(program, name)
       after("getUniformLocation")
       return res
    }
    override fun getBooleanv(pname: Int, data: KmlBuffer): Unit {
       before("getBooleanv")
       val res = parent.getBooleanv(pname, data)
       after("getBooleanv")
       return res
    }
    override fun getBufferParameteriv(target: Int, pname: Int, params: KmlBuffer): Unit {
       before("getBufferParameteriv")
       val res = parent.getBufferParameteriv(target, pname, params)
       after("getBufferParameteriv")
       return res
    }
    override fun getError(): Int {
       before("getError")
       val res = parent.getError()
       after("getError")
       return res
    }
    override fun getFloatv(pname: Int, data: KmlBuffer): Unit {
       before("getFloatv")
       val res = parent.getFloatv(pname, data)
       after("getFloatv")
       return res
    }
    override fun getFramebufferAttachmentParameteriv(target: Int, attachment: Int, pname: Int, params: KmlBuffer): Unit {
       before("getFramebufferAttachmentParameteriv")
       val res = parent.getFramebufferAttachmentParameteriv(target, attachment, pname, params)
       after("getFramebufferAttachmentParameteriv")
       return res
    }
    override fun getIntegerv(pname: Int, data: KmlBuffer): Unit {
       before("getIntegerv")
       val res = parent.getIntegerv(pname, data)
       after("getIntegerv")
       return res
    }
    override fun getProgramInfoLog(program: Int, bufSize: Int, length: KmlBuffer, infoLog: KmlBuffer): Unit {
       before("getProgramInfoLog")
       val res = parent.getProgramInfoLog(program, bufSize, length, infoLog)
       after("getProgramInfoLog")
       return res
    }
    override fun getRenderbufferParameteriv(target: Int, pname: Int, params: KmlBuffer): Unit {
       before("getRenderbufferParameteriv")
       val res = parent.getRenderbufferParameteriv(target, pname, params)
       after("getRenderbufferParameteriv")
       return res
    }
    override fun getProgramiv(program: Int, pname: Int, params: KmlBuffer): Unit {
       before("getProgramiv")
       val res = parent.getProgramiv(program, pname, params)
       after("getProgramiv")
       return res
    }
    override fun getShaderiv(shader: Int, pname: Int, params: KmlBuffer): Unit {
       before("getShaderiv")
       val res = parent.getShaderiv(shader, pname, params)
       after("getShaderiv")
       return res
    }
    override fun getShaderInfoLog(shader: Int, bufSize: Int, length: KmlBuffer, infoLog: KmlBuffer): Unit {
       before("getShaderInfoLog")
       val res = parent.getShaderInfoLog(shader, bufSize, length, infoLog)
       after("getShaderInfoLog")
       return res
    }
    override fun getShaderPrecisionFormat(shadertype: Int, precisiontype: Int, range: KmlBuffer, precision: KmlBuffer): Unit {
       before("getShaderPrecisionFormat")
       val res = parent.getShaderPrecisionFormat(shadertype, precisiontype, range, precision)
       after("getShaderPrecisionFormat")
       return res
    }
    override fun getShaderSource(shader: Int, bufSize: Int, length: KmlBuffer, source: KmlBuffer): Unit {
       before("getShaderSource")
       val res = parent.getShaderSource(shader, bufSize, length, source)
       after("getShaderSource")
       return res
    }
    override fun getString(name: Int): String {
       before("getString")
       val res = parent.getString(name)
       after("getString")
       return res
    }
    override fun getTexParameterfv(target: Int, pname: Int, params: KmlBuffer): Unit {
       before("getTexParameterfv")
       val res = parent.getTexParameterfv(target, pname, params)
       after("getTexParameterfv")
       return res
    }
    override fun getTexParameteriv(target: Int, pname: Int, params: KmlBuffer): Unit {
       before("getTexParameteriv")
       val res = parent.getTexParameteriv(target, pname, params)
       after("getTexParameteriv")
       return res
    }
    override fun getUniformfv(program: Int, location: Int, params: KmlBuffer): Unit {
       before("getUniformfv")
       val res = parent.getUniformfv(program, location, params)
       after("getUniformfv")
       return res
    }
    override fun getUniformiv(program: Int, location: Int, params: KmlBuffer): Unit {
       before("getUniformiv")
       val res = parent.getUniformiv(program, location, params)
       after("getUniformiv")
       return res
    }
    override fun getVertexAttribfv(index: Int, pname: Int, params: KmlBuffer): Unit {
       before("getVertexAttribfv")
       val res = parent.getVertexAttribfv(index, pname, params)
       after("getVertexAttribfv")
       return res
    }
    override fun getVertexAttribiv(index: Int, pname: Int, params: KmlBuffer): Unit {
       before("getVertexAttribiv")
       val res = parent.getVertexAttribiv(index, pname, params)
       after("getVertexAttribiv")
       return res
    }
    override fun getVertexAttribPointerv(index: Int, pname: Int, pointer: KmlBuffer): Unit {
       before("getVertexAttribPointerv")
       val res = parent.getVertexAttribPointerv(index, pname, pointer)
       after("getVertexAttribPointerv")
       return res
    }
    override fun hint(target: Int, mode: Int): Unit {
       before("hint")
       val res = parent.hint(target, mode)
       after("hint")
       return res
    }
    override fun isBuffer(buffer: Int): Boolean {
       before("isBuffer")
       val res = parent.isBuffer(buffer)
       after("isBuffer")
       return res
    }
    override fun isEnabled(cap: Int): Boolean {
       before("isEnabled")
       val res = parent.isEnabled(cap)
       after("isEnabled")
       return res
    }
    override fun isFramebuffer(framebuffer: Int): Boolean {
       before("isFramebuffer")
       val res = parent.isFramebuffer(framebuffer)
       after("isFramebuffer")
       return res
    }
    override fun isProgram(program: Int): Boolean {
       before("isProgram")
       val res = parent.isProgram(program)
       after("isProgram")
       return res
    }
    override fun isRenderbuffer(renderbuffer: Int): Boolean {
       before("isRenderbuffer")
       val res = parent.isRenderbuffer(renderbuffer)
       after("isRenderbuffer")
       return res
    }
    override fun isShader(shader: Int): Boolean {
       before("isShader")
       val res = parent.isShader(shader)
       after("isShader")
       return res
    }
    override fun isTexture(texture: Int): Boolean {
       before("isTexture")
       val res = parent.isTexture(texture)
       after("isTexture")
       return res
    }
    override fun lineWidth(width: Float): Unit {
       before("lineWidth")
       val res = parent.lineWidth(width)
       after("lineWidth")
       return res
    }
    override fun linkProgram(program: Int): Unit {
       before("linkProgram")
       val res = parent.linkProgram(program)
       after("linkProgram")
       return res
    }
    override fun pixelStorei(pname: Int, param: Int): Unit {
       before("pixelStorei")
       val res = parent.pixelStorei(pname, param)
       after("pixelStorei")
       return res
    }
    override fun polygonOffset(factor: Float, units: Float): Unit {
       before("polygonOffset")
       val res = parent.polygonOffset(factor, units)
       after("polygonOffset")
       return res
    }
    override fun readPixels(x: Int, y: Int, width: Int, height: Int, format: Int, type: Int, pixels: KmlBuffer): Unit {
       before("readPixels")
       val res = parent.readPixels(x, y, width, height, format, type, pixels)
       after("readPixels")
       return res
    }
    override fun releaseShaderCompiler(): Unit {
       before("releaseShaderCompiler")
       val res = parent.releaseShaderCompiler()
       after("releaseShaderCompiler")
       return res
    }
    override fun renderbufferStorage(target: Int, internalformat: Int, width: Int, height: Int): Unit {
       before("renderbufferStorage")
       val res = parent.renderbufferStorage(target, internalformat, width, height)
       after("renderbufferStorage")
       return res
    }
    override fun sampleCoverage(value: Float, invert: Boolean): Unit {
       before("sampleCoverage")
       val res = parent.sampleCoverage(value, invert)
       after("sampleCoverage")
       return res
    }
    override fun scissor(x: Int, y: Int, width: Int, height: Int): Unit {
       before("scissor")
       val res = parent.scissor(x, y, width, height)
       after("scissor")
       return res
    }
    override fun shaderBinary(count: Int, shaders: KmlBuffer, binaryformat: Int, binary: KmlBuffer, length: Int): Unit {
       before("shaderBinary")
       val res = parent.shaderBinary(count, shaders, binaryformat, binary, length)
       after("shaderBinary")
       return res
    }
    override fun shaderSource(shader: Int, string: String): Unit {
       before("shaderSource")
       val res = parent.shaderSource(shader, string)
       after("shaderSource")
       return res
    }
    override fun stencilFunc(func: Int, ref: Int, mask: Int): Unit {
       before("stencilFunc")
       val res = parent.stencilFunc(func, ref, mask)
       after("stencilFunc")
       return res
    }
    override fun stencilFuncSeparate(face: Int, func: Int, ref: Int, mask: Int): Unit {
       before("stencilFuncSeparate")
       val res = parent.stencilFuncSeparate(face, func, ref, mask)
       after("stencilFuncSeparate")
       return res
    }
    override fun stencilMask(mask: Int): Unit {
       before("stencilMask")
       val res = parent.stencilMask(mask)
       after("stencilMask")
       return res
    }
    override fun stencilMaskSeparate(face: Int, mask: Int): Unit {
       before("stencilMaskSeparate")
       val res = parent.stencilMaskSeparate(face, mask)
       after("stencilMaskSeparate")
       return res
    }
    override fun stencilOp(fail: Int, zfail: Int, zpass: Int): Unit {
       before("stencilOp")
       val res = parent.stencilOp(fail, zfail, zpass)
       after("stencilOp")
       return res
    }
    override fun stencilOpSeparate(face: Int, sfail: Int, dpfail: Int, dppass: Int): Unit {
       before("stencilOpSeparate")
       val res = parent.stencilOpSeparate(face, sfail, dpfail, dppass)
       after("stencilOpSeparate")
       return res
    }
    override fun texImage2D(target: Int, level: Int, internalformat: Int, width: Int, height: Int, border: Int, format: Int, type: Int, pixels: KmlBuffer): Unit {
       before("texImage2D")
       val res = parent.texImage2D(target, level, internalformat, width, height, border, format, type, pixels)
       after("texImage2D")
       return res
    }
    override fun texImage2D(target: Int, level: Int, internalformat: Int, format: Int, type: Int, data: KmlNativeImageData): Unit {
       before("texImage2D")
       val res = parent.texImage2D(target, level, internalformat, format, type, data)
       after("texImage2D")
       return res
    }
    override fun texParameterf(target: Int, pname: Int, param: Float): Unit {
       before("texParameterf")
       val res = parent.texParameterf(target, pname, param)
       after("texParameterf")
       return res
    }
    override fun texParameterfv(target: Int, pname: Int, params: KmlBuffer): Unit {
       before("texParameterfv")
       val res = parent.texParameterfv(target, pname, params)
       after("texParameterfv")
       return res
    }
    override fun texParameteri(target: Int, pname: Int, param: Int): Unit {
       before("texParameteri")
       val res = parent.texParameteri(target, pname, param)
       after("texParameteri")
       return res
    }
    override fun texParameteriv(target: Int, pname: Int, params: KmlBuffer): Unit {
       before("texParameteriv")
       val res = parent.texParameteriv(target, pname, params)
       after("texParameteriv")
       return res
    }
    override fun texSubImage2D(target: Int, level: Int, xoffset: Int, yoffset: Int, width: Int, height: Int, format: Int, type: Int, pixels: KmlBuffer): Unit {
       before("texSubImage2D")
       val res = parent.texSubImage2D(target, level, xoffset, yoffset, width, height, format, type, pixels)
       after("texSubImage2D")
       return res
    }
    override fun uniform1f(location: Int, v0: Float): Unit {
       before("uniform1f")
       val res = parent.uniform1f(location, v0)
       after("uniform1f")
       return res
    }
    override fun uniform1fv(location: Int, count: Int, value: KmlBuffer): Unit {
       before("uniform1fv")
       val res = parent.uniform1fv(location, count, value)
       after("uniform1fv")
       return res
    }
    override fun uniform1i(location: Int, v0: Int): Unit {
       before("uniform1i")
       val res = parent.uniform1i(location, v0)
       after("uniform1i")
       return res
    }
    override fun uniform1iv(location: Int, count: Int, value: KmlBuffer): Unit {
       before("uniform1iv")
       val res = parent.uniform1iv(location, count, value)
       after("uniform1iv")
       return res
    }
    override fun uniform2f(location: Int, v0: Float, v1: Float): Unit {
       before("uniform2f")
       val res = parent.uniform2f(location, v0, v1)
       after("uniform2f")
       return res
    }
    override fun uniform2fv(location: Int, count: Int, value: KmlBuffer): Unit {
       before("uniform2fv")
       val res = parent.uniform2fv(location, count, value)
       after("uniform2fv")
       return res
    }
    override fun uniform2i(location: Int, v0: Int, v1: Int): Unit {
       before("uniform2i")
       val res = parent.uniform2i(location, v0, v1)
       after("uniform2i")
       return res
    }
    override fun uniform2iv(location: Int, count: Int, value: KmlBuffer): Unit {
       before("uniform2iv")
       val res = parent.uniform2iv(location, count, value)
       after("uniform2iv")
       return res
    }
    override fun uniform3f(location: Int, v0: Float, v1: Float, v2: Float): Unit {
       before("uniform3f")
       val res = parent.uniform3f(location, v0, v1, v2)
       after("uniform3f")
       return res
    }
    override fun uniform3fv(location: Int, count: Int, value: KmlBuffer): Unit {
       before("uniform3fv")
       val res = parent.uniform3fv(location, count, value)
       after("uniform3fv")
       return res
    }
    override fun uniform3i(location: Int, v0: Int, v1: Int, v2: Int): Unit {
       before("uniform3i")
       val res = parent.uniform3i(location, v0, v1, v2)
       after("uniform3i")
       return res
    }
    override fun uniform3iv(location: Int, count: Int, value: KmlBuffer): Unit {
       before("uniform3iv")
       val res = parent.uniform3iv(location, count, value)
       after("uniform3iv")
       return res
    }
    override fun uniform4f(location: Int, v0: Float, v1: Float, v2: Float, v3: Float): Unit {
       before("uniform4f")
       val res = parent.uniform4f(location, v0, v1, v2, v3)
       after("uniform4f")
       return res
    }
    override fun uniform4fv(location: Int, count: Int, value: KmlBuffer): Unit {
       before("uniform4fv")
       val res = parent.uniform4fv(location, count, value)
       after("uniform4fv")
       return res
    }
    override fun uniform4i(location: Int, v0: Int, v1: Int, v2: Int, v3: Int): Unit {
       before("uniform4i")
       val res = parent.uniform4i(location, v0, v1, v2, v3)
       after("uniform4i")
       return res
    }
    override fun uniform4iv(location: Int, count: Int, value: KmlBuffer): Unit {
       before("uniform4iv")
       val res = parent.uniform4iv(location, count, value)
       after("uniform4iv")
       return res
    }
    override fun uniformMatrix2fv(location: Int, count: Int, transpose: Boolean, value: KmlBuffer): Unit {
       before("uniformMatrix2fv")
       val res = parent.uniformMatrix2fv(location, count, transpose, value)
       after("uniformMatrix2fv")
       return res
    }
    override fun uniformMatrix3fv(location: Int, count: Int, transpose: Boolean, value: KmlBuffer): Unit {
       before("uniformMatrix3fv")
       val res = parent.uniformMatrix3fv(location, count, transpose, value)
       after("uniformMatrix3fv")
       return res
    }
    override fun uniformMatrix4fv(location: Int, count: Int, transpose: Boolean, value: KmlBuffer): Unit {
       before("uniformMatrix4fv")
       val res = parent.uniformMatrix4fv(location, count, transpose, value)
       after("uniformMatrix4fv")
       return res
    }
    override fun useProgram(program: Int): Unit {
       before("useProgram")
       val res = parent.useProgram(program)
       after("useProgram")
       return res
    }
    override fun validateProgram(program: Int): Unit {
       before("validateProgram")
       val res = parent.validateProgram(program)
       after("validateProgram")
       return res
    }
    override fun vertexAttrib1f(index: Int, x: Float): Unit {
       before("vertexAttrib1f")
       val res = parent.vertexAttrib1f(index, x)
       after("vertexAttrib1f")
       return res
    }
    override fun vertexAttrib1fv(index: Int, v: KmlBuffer): Unit {
       before("vertexAttrib1fv")
       val res = parent.vertexAttrib1fv(index, v)
       after("vertexAttrib1fv")
       return res
    }
    override fun vertexAttrib2f(index: Int, x: Float, y: Float): Unit {
       before("vertexAttrib2f")
       val res = parent.vertexAttrib2f(index, x, y)
       after("vertexAttrib2f")
       return res
    }
    override fun vertexAttrib2fv(index: Int, v: KmlBuffer): Unit {
       before("vertexAttrib2fv")
       val res = parent.vertexAttrib2fv(index, v)
       after("vertexAttrib2fv")
       return res
    }
    override fun vertexAttrib3f(index: Int, x: Float, y: Float, z: Float): Unit {
       before("vertexAttrib3f")
       val res = parent.vertexAttrib3f(index, x, y, z)
       after("vertexAttrib3f")
       return res
    }
    override fun vertexAttrib3fv(index: Int, v: KmlBuffer): Unit {
       before("vertexAttrib3fv")
       val res = parent.vertexAttrib3fv(index, v)
       after("vertexAttrib3fv")
       return res
    }
    override fun vertexAttrib4f(index: Int, x: Float, y: Float, z: Float, w: Float): Unit {
       before("vertexAttrib4f")
       val res = parent.vertexAttrib4f(index, x, y, z, w)
       after("vertexAttrib4f")
       return res
    }
    override fun vertexAttrib4fv(index: Int, v: KmlBuffer): Unit {
       before("vertexAttrib4fv")
       val res = parent.vertexAttrib4fv(index, v)
       after("vertexAttrib4fv")
       return res
    }
    override fun vertexAttribPointer(index: Int, size: Int, type: Int, normalized: Boolean, stride: Int, pointer: Int): Unit {
       before("vertexAttribPointer")
       val res = parent.vertexAttribPointer(index, size, type, normalized, stride, pointer)
       after("vertexAttribPointer")
       return res
    }
    override fun viewport(x: Int, y: Int, width: Int, height: Int): Unit {
       before("viewport")
       val res = parent.viewport(x, y, width, height)
       after("viewport")
       return res
    }
}
class LogKmlGlProxy(parent: KmlGl) : KmlGlProxy(parent) {
   override fun before(name: String): Unit = run { println("before: $name") }
   override fun after(name: String): Unit = run { println("after: $name") }
}
class CheckErrorsKmlGlProxy(parent: KmlGl) : KmlGlProxy(parent) {
   override fun after(name: String): Unit = run { val error = parent.getError(); if (error != NO_ERROR) { println("glError: $error calling $name"); throw RuntimeException("glError: $error calling $name") } }
}
